# Generated by Django 3.1.7 on 2021-04-08 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20210408_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='likedby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
