# Generated by Django 3.2 on 2021-04-15 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
