# Generated by Django 3.1.7 on 2021-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='karma_score',
            field=models.IntegerField(default=0),
        ),
    ]
