# Generated by Django 3.1.7 on 2021-04-15 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='_mycustomuser_followed_list_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
