# Generated by Django 3.1.7 on 2021-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210407_1950'),
        ('IMDB_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='seen_list',
            field=models.ManyToManyField(blank=True, related_name='seen', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watch', to='movies.Movie'),
        ),
    ]
