# Generated by Django 3.1.7 on 2021-04-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0002_auto_20210414_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
