# Generated by Django 3.1.7 on 2021-04-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0003_auto_20210408_0058'),
        ('IMDB_user', '0002_mycustomuser_karma_score'),
    ]

    operations = [
    ]
