# Generated by Django 3.1.7 on 2021-04-19 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB_user', '0003_auto_20210415_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
