# Generated by Django 3.1.7 on 2021-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seen',
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imbd_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
