# Generated by Django 3.1.7 on 2021-04-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
