# Generated by Django 3.1.7 on 2021-04-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210407_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
    ]
