# Generated by Django 3.1.7 on 2021-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210408_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
