# Generated by Django 3.1.7 on 2021-04-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_name'),
        ('movies', '0002_auto_20210407_1950'),
    ]

    operations = [
    ]
