# Generated by Django 3.1.7 on 2021-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210408_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(default=''),
        ),
    ]
