# Generated by Django 3.1.7 on 2021-04-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210408_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='tmdb_id',
        ),
    ]
